# --------------------------------------------------
# 01. NumPy Basics
# --------------------------------------------------

In [5]:
import numpy as np      # numerical processing library

# numpy array creation
numbers = np.array([10,20,30,40,50])
print(numbers)

# inspect the array
print("Array shape:", numbers.shape)    # prints the dimensions of the array
print("Array dtype:", numbers.dtype)    # prints the data type of the array elements
print("Array size:", numbers.size)      # prints the total number of elements in the array
print("Array dimensions:", numbers.ndim)      # prints the number of dimensions of the array

[10 20 30 40 50]
Array shape: (5,)
Array dtype: int64
Array size: 5
Array dimensions: 1


# --------------------------------------------------
# 02. 2D Arrays
# --------------------------------------------------

In [6]:
matrix = np.array([[1,2,3],[4,5,6]])    # creating a 2D array
print(matrix)

print("Matrix shape:", matrix.shape)    # prints the dimensions of the matrix
print("Matrix dtype:", matrix.dtype)    # prints the data type of the matrix elements
print("Matrix size:", matrix.size)      # prints the total number of elements in the matrix
print("Matrix dimensions:", matrix.ndim)      # prints the number of dimensions of the matrix

[[1 2 3]
 [4 5 6]]
Matrix shape: (2, 3)
Matrix dtype: int64
Matrix size: 6
Matrix dimensions: 2


# --------------------------------------------------
# 03. Array Indexing & Slicing
# --------------------------------------------------

In [ ]:
# for 1d array indexing
numbers = np.array([10,20,30,40,50])
print(numbers[0])   # prints the first element of the array
print(numbers[2])   # prints the third element of the array
print(numbers[-1])  # prints the last element of the array

# for id array slicing
print(numbers[1:4])  # prints elements from index 1 to 3

# for 2d array indexing
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix[0,0])  # prints the element at row 0, column 0
print(matrix[1,2])  # prints the element at row 1, column 2
print(matrix[-1,-1]) # prints the last element of the matrix

# for 2d array slicing
print(matrix[0,:])  # prints the first row of the matrix
print(matrix[:,1])  # prints the second column of the matrix
print(matrix[0:1,1:3])  # prints elements from row 0 to 1 and columns 1 to 2



10
30
50
[20 30 40]
1
6
6
[1 2 3]
[2 5]
[]


# --------------------------------------------------
# 04. Array Operations
# --------------------------------------------------

In [ ]:
# NumPy is powerful because you can perform operations on entire arrays and this is called vectorization.

numbers = np.array([10, 20, 30, 40])
print(numbers + 5)              # adds 5 to each element of the array
print(numbers * 2)              # multiplies each element of the array by 2

# addition of two arrays
a = np.array([10, 20, 30])      # creating a 1D array
b = np.array([1, 2, 3])         # creating another 1D array
print(a + b)                    # adds the corresponding elements of the two arrays
print(a - b)                    # subtracts the corresponding elements of the two arrays
print(a * b)                    # multiplies the corresponding elements of the two arrays
print(a / b)                    # divides the corresponding elements of the two arrays


[15 25 35 45]


# --------------------------------------------------
# 05. NumPy Statistics
# --------------------------------------------------

In [ ]:
# This is important because AI/ML works heavily with numerical data.

scores = np.array([65, 72, 80, 90, 75])
print(scores)                               # prints the original scores
print("Mean/Average:", np.mean(scores))             # calculates and prints the mean of the scores
print("Median:", np.median(scores))         # calculates and prints the median of the scores
print("Standard Deviation:", np.std(scores))  # calculates and prints the standard deviation of the scores
print("Variance:", np.var(scores))           # calculates and prints the variance of the scores
print("Minimum:", np.min(scores))             # finds and prints the minimum score
print("Maximum:", np.max(scores))             # finds and prints the maximum score
print("Sum:", np.sum(scores))                 # calculates and prints the sum of the scores
print("Sorted Scores:", np.sort(scores))      # sorts and prints the scores in ascending order
print("Unique Scores:", np.unique(scores))    # finds and prints the unique scores

[65 72 80 90 75]
Mean: 76.4
Median: 75.0
Average: 76.4
Standard Deviation: 8.357032966310472
Variance: 69.84
Minimum: 65
Maximum: 90
Sum: 382
Sorted Scores: [65 72 75 80 90]
Unique Scores: [65 72 75 80 90]


# --------------------------------------------------
# 06. Broadcasting
# --------------------------------------------------

In [16]:
#Broadcasting means NumPy can perform an operation between arrays of different shapes by automatically adjusting the smaller value/array to work with the larger one.

# array + single number
array = np.array([10, 20, 30, 40])
print(array + 5)                     # adds 5 to each element of the array
# Conceptually, NumPy treats it like:
    #10 + 5
    #20 + 5
    #30 + 5
    #40 + 5

# 2D array + 1D array
matrix = np.array([[10,20,30],
                   [40,50,60]])
vector = np.array([10,20,30])
print(matrix + vector)               # adds the vector to each row of the matrix
# NumPy effectively applies:
    # 10  20  30   +   10  20  30
    # 40  50  60   +   10  20  30
    # if the shapes are compatible, it will broadcast the smaller array across the larger one.

[15 25 35 45]
[[20 40 60]
 [50 70 90]]


# --------------------------------------------------
# 07. Filtering & Conditions
# --------------------------------------------------

In [ ]:
# Filtering is very useful in data analysis and machine learning because you often need to select specific data fulfilling certain conditions.
scores = np.array([45,67,82,35,91,58])      # creating a 1D array of scores
print(scores > 60)                          # prints a boolean array indicating which scores are greater than 60 (true/false)
print(scores[scores > 60])                  # filters and prints the scores that are greater than 60

# Use & for AND, | for OR, and ~ for NOT  (when combining multiple conditions)
print(scores[(scores > 60) & (scores < 90)])  # filters scores between 60 and 90
print(scores[(scores < 50) | (scores > 80)])  # filters scores less than 50 or greater than 80
print(scores[~(scores > 60)])                 # filters scores that are NOT greater than 60


[False  True  True False  True False]
[67 82 91]
[67 82]
[45 82 35 91]
[45 35 58]


# --------------------------------------------------
# 08. NumPy Practice
# --------------------------------------------------

# Task 1 — Dataset
Create data = 12, 25, 18, 40, 35, 50, 22, 60

    # Find the total

    # Find the average

    # Find the minimum

    # Find the maximum
    
    # Find the standard deviation


In [21]:
numbers = np.array([12, 25, 18, 40, 35, 50, 20, 60])
print("Total: ",np.sum(numbers))
print("Average: ", np.average(numbers))
print("Minimum: ", np.min(numbers))
print("Maximum: ", np.max(numbers))
print("Standard Deviation: ", np.std(numbers))

Total:  260
Average:  32.5
Minimum:  12
Maximum:  60
Standard Deviation:  15.684387141358123


# Task 2 - Filtering
Using same dataset

    #Print values greater than 30

    #Print values less than 25

    #Print values between 20 and 50

In [23]:
numbers = np.array([12, 25, 18, 40, 35, 50, 20, 60])
print("Values > 30: ", numbers[numbers > 30])
print("Values < 25: ", numbers[numbers < 25])
print("Values between 20 and 50: ", numbers[(numbers > 20) & (numbers < 50)])

Values > 30:  [40 35 50 60]
Values < 25:  [12 18 20]
Values between 20 and 50:  [25 40 35]


# Task 3 — 2D Array

Create 2D array= [80, 75, 90]
                 [60, 85, 70]
                 [95, 88, 92]

    # Print the shape
 
    # Print the dimensions
 
    # Print the mark 85
 
    # Print the entire second row
 
    # Calculate the average of all marks

In [ ]:
numbers = np.array([[80, 75, 90],
                   [60, 85, 70],
                   [95, 88, 92]])
print("Shape of the 2D array: ", numbers.shape)
print("Dimentions of the 2D array: ", numbers.ndim)
print(numbers[1, 1])
print(numbers[1, :])
print("Average of all marks: ", np.average(numbers))

Shape of the 2D array:  (3, 3)
Dimentions of the 2D array:  2
85
[60 85 70]
Average of all marks:  81.66666666666667


# Task 4 — Broadcasting
Using:  marks = [
    [80, 75, 90],
    [60, 85, 70],
    [95, 88, 92]
]

Add bonus to marks:
    bonus = [5, 5, 5]

    # Print the updated marks

In [27]:
numbers = np.array([[80, 75, 90],
                   [60, 85, 70],
                   [95, 88, 92]])
bonus = np.array([5, 5, 5])

print("Updated Marks with Bonus: ", numbers + bonus)

Updated Marks with Bonus:  [[ 85  80  95]
 [ 65  90  75]
 [100  93  97]]
